### ISSUE TITLE
project roots with spaces cause error

### ISSUE THREAD

**Issue by pitkling** [notjedi/nvim-rooter.lua#4] opened 2022-06-21 22:00 UTC
I noticed that your plugin did not work for one of my project roots. When running `:RooterToggle` manually I get an error message of the form.

``
Can't find directory "<escaped_path_to_project_root>" in cdpath
``

To me it seems the problem is the escaping done in `change_dir` (line 20 in code reference below). If I delete that line, everything seems to work, at least on my system. Is that escaping really required or does `vim.api.nvim_set_current_dir` take actually unescaped directory paths?

https://github.com/notjedi/nvim-rooter.lua/blob/156a1f536882380445796f105dd017962a206034/lua/nvim-rooter.lua#L19-L22

**Comment by pitkling** [comment] 2022-06-24 16:27
Sure, take your time and good luck with those exams. My operating system is macOS (12.4, Monterey).

**Comment by notjedi** [comment] 2022-06-24 16:32
can you type in the path of the directory that we are dealing with? so i can check if i can reproduce it on my local linux machine

**Comment by pitkling** [comment] 2022-06-26 12:46
I just tested it with two pseudo-projects:
* opening ~/Downloads/test1/main.tex
* opening ~/Downlodas/test 1/main.tex
In both cases I initialized an empty git repository via `git init` before opening them. In the first one the project root was correctly set, in the second one not. After uncommenting line 20, it works in both cases. I checked Neovim's help information about `nvim_set_current_dir` but couldn't find any information whether it expects an escaped or unescaped path.

**Comment by notjedi** [comment] 2022-06-26 12:49
so we are dealing with spaces. well usually a space needs to be escaped and that's what i'm doing. will look into it. thank you.

**Comment by notjedi** [comment] 2022-06-26 13:00
@pitkling seems like you are right, `vim.fn.fnameescape(dir)` is not necessary because we are passing in the path as a string so we don't have to escape white spaces or any special chars for that matter. on the vim side of things `fnameescape` is necessary because we would use `:cd DIR_NAME` which would result in an error if we don't escape special chars. thanks for reporting, will push a commit fixing this issue.

**Comment by notjedi** [comment] 2022-06-26 13:01
@pitkling fixed in 140c5a886ffa2de45a469d2ce1e2b53dd97798bb

**Closed** 2022-06-26 13:01 UTC
Labels: bug, good first issue

**Comment by pitkling** [comment] 2022-06-26 13:10
Great, thanks for the quick fix!
